### ISSUE TITLE
missing reference to the original source

### ISSUE THREAD

**Issue by caramel-cranberries** [mark260486/s_lem#1]
hello, thank you for this amazing program, 

My father was telling me for years about the original flowchart by Mr Lem, which was published in the Czech youth magazine, but he was never able to find it again. Do you have any idea where to find it, in any language, please?

Thank you very much

**Comment by mark260486** [comment]
Hello! 

Thanks a lot :)

![image](https://user-images.githubusercontent.com/49118755/201281394-b173a5ad-a9c6-4cb0-85fc-ead30b08b7b6.png)

**Comment by mcepl** [comment]
Thank you so much!
